// Generated by @nextnode-solutions/worker-types - do not edit.
// Regenerate with `worker-types gen`; source of truth is nextnode.toml.

/// <reference types="@cloudflare/workers-types" />

declare namespace Cloudflare {
	interface Env {
		readonly API: Fetcher
		readonly ASSETS: Fetcher
		readonly SITE_URL: string
	}
}

interface Env extends Cloudflare.Env {}
